sudo: required

services:
  - docker

script: 
  - docker login -u jamesemwallis -p $PASSWORD
  - docker build -t jamesemwallis/james-wallis.com:next
  - docker push jamesemwallis/james-wallis.com:next