sudo: required

services:
  - docker

script: 
  - docker login -u jamesemwallis -p $PASSWORD
  # Output something every 10 minutes or Travis kills the job
  - while sleep 5m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - docker build -t jamesemwallis/wallis.dev:latest . 
  # Killing background sleep loop
  - kill %1
  - docker push jamesemwallis/wallis.dev:latest
